services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ensures Linux Docker also works

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4173:80"
    depends_on:
      - backend
